name: Run Tests
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node
      volumes:
        - my_docker_volume:/volume_mount
      
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: node js exists check
        run: node -v
        
      - name: node js exists check
        run: node -v
